spring.application.name=laboratorio-owasp

# H2 em memoria, populado por schema.sql + data.sql
spring.datasource.url=jdbc:h2:mem:labowasp;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always

# Nao logar stack traces detalhados em producao (o proprio A05 seria vazar isso)
server.error.include-message=never
server.error.include-stacktrace=never
